//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumingRest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/BookWcfService1")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBookService2")]
    public interface IBookService2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/GetBookList", ReplyAction="http://tempuri.org/IBookService2/GetBookListResponse")]
        ConsumingRest.ServiceReference1.Book[] GetBookList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/GetBookList", ReplyAction="http://tempuri.org/IBookService2/GetBookListResponse")]
        System.Threading.Tasks.Task<ConsumingRest.ServiceReference1.Book[]> GetBookListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/GetBookId", ReplyAction="http://tempuri.org/IBookService2/GetBookIdResponse")]
        ConsumingRest.ServiceReference1.Book GetBookId(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/GetBookId", ReplyAction="http://tempuri.org/IBookService2/GetBookIdResponse")]
        System.Threading.Tasks.Task<ConsumingRest.ServiceReference1.Book> GetBookIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/AddBook", ReplyAction="http://tempuri.org/IBookService2/AddBookResponse")]
        string AddBook(ConsumingRest.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/AddBook", ReplyAction="http://tempuri.org/IBookService2/AddBookResponse")]
        System.Threading.Tasks.Task<string> AddBookAsync(ConsumingRest.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/UpDateBook", ReplyAction="http://tempuri.org/IBookService2/UpDateBookResponse")]
        string UpDateBook(ConsumingRest.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/UpDateBook", ReplyAction="http://tempuri.org/IBookService2/UpDateBookResponse")]
        System.Threading.Tasks.Task<string> UpDateBookAsync(ConsumingRest.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/DeleteBook", ReplyAction="http://tempuri.org/IBookService2/DeleteBookResponse")]
        string DeleteBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookService2/DeleteBook", ReplyAction="http://tempuri.org/IBookService2/DeleteBookResponse")]
        System.Threading.Tasks.Task<string> DeleteBookAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookService2Channel : ConsumingRest.ServiceReference1.IBookService2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookService2Client : System.ServiceModel.ClientBase<ConsumingRest.ServiceReference1.IBookService2>, ConsumingRest.ServiceReference1.IBookService2 {
        
        public BookService2Client() {
        }
        
        public BookService2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookService2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookService2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookService2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsumingRest.ServiceReference1.Book[] GetBookList() {
            return base.Channel.GetBookList();
        }
        
        public System.Threading.Tasks.Task<ConsumingRest.ServiceReference1.Book[]> GetBookListAsync() {
            return base.Channel.GetBookListAsync();
        }
        
        public ConsumingRest.ServiceReference1.Book GetBookId(string id) {
            return base.Channel.GetBookId(id);
        }
        
        public System.Threading.Tasks.Task<ConsumingRest.ServiceReference1.Book> GetBookIdAsync(string id) {
            return base.Channel.GetBookIdAsync(id);
        }
        
        public string AddBook(ConsumingRest.ServiceReference1.Book book) {
            return base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task<string> AddBookAsync(ConsumingRest.ServiceReference1.Book book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public string UpDateBook(ConsumingRest.ServiceReference1.Book book) {
            return base.Channel.UpDateBook(book);
        }
        
        public System.Threading.Tasks.Task<string> UpDateBookAsync(ConsumingRest.ServiceReference1.Book book) {
            return base.Channel.UpDateBookAsync(book);
        }
        
        public string DeleteBook(string id) {
            return base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBookAsync(string id) {
            return base.Channel.DeleteBookAsync(id);
        }
    }
}
